# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=255)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('modify_time', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'bill',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='accounting_book.User'),
        ),
    ]
